### ISSUE TITLE
java.net.BindException when using :james-server:runJamesServer task

### ISSUE THREAD

**Issue by dleangen** [ieugen/james-self-hosting-sandbox#11]
I think the gradle `:james-server:runJamesServer` task is nice, but for some reason the ports won't bind when I use this on my Mac.

```
Wrapped by: org.jboss.netty.channel.ChannelException: Failed to bind to: /127.0.0.9:993
...
Caused by: java.net.BindException: Can't assign requested address
```

The strange thing is that when I run a port scan, I notice that nothing seems to be using these ports.

<img width="681" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/9663141/84858046-59265c00-b0a5-11ea-9558-9f86a2227cfd.png">

**Comment by chibenwa** [comment]
993 is imap, check imapserver.xml (by default SSL is binding port 993) and run with "sudo" in order to be able to bind ports below 1024.

**Comment by ieugen** [comment]
Don't use ports < 1000 locally. They require root.

**Comment by dleangen** [comment]
I was just running the scripts. I take it you don't care to hear any feedback. I'll probably start my own project with a development environment that I am more used to if this is not intended for collaboration. I thought this this would be something that users would use. I didn't realize that it was only for your own personal use. Sorry that I misunderstood!
