### ISSUE TITLE
How to load in IDE?

### ISSUE THREAD

**Issue by dleangen** [ieugen/james-self-hosting-sandbox#12]
I assume that the idea here is that the sandbox allows "Extension Developers" to build and test extensions.

I am not sure what the expectation is in terms of how to load the project into my IDE (Eclipse).

Are you able to explain? I would like to test out what you have done here. :-)

**Comment by ieugen** [comment]
It's a gradle project. It can be used in any IDE that has support for Gradle (most of them by now). 

I use Intellij and open the build.gradle. 
See https://projects.eclipse.org/projects/tools.buildship 
https://www.vogella.com/tutorials/EclipseGradle/article.html

**Comment by ieugen** [comment]
I will do a couple of videos and post them on youtube in the next days. 
What are you interested in?

**Comment by dleangen** [comment]
Well, at first I thought this project was for the community. If it is only for your private consumption, then I will probably just create an environment that I am more used to using instead of spending time trying to learn how you do things. I would be willing to spend the time if it were to be helpful to the community.

Sorry I had misunderstood your intentions.
