### ISSUE TITLE
What does "self hosting" mean?

### ISSUE THREAD

**Issue by dleangen** [ieugen/james-self-hosting-sandbox#9]
The name of the project is "Jame Self Hosting Sandbox", and I see the term "self hosting" in a few places... So it sounds like it is important, but what is that intended to mean?

I would like to understand better the intention behind the term.

**Comment by chibenwa** [comment]
I would say "self hosting" means individuals having bought a domain name and want to install their own mail server for hosting their personal emails. Volumetry is small. They want control on their data.

One generally tricky point about this kind of set up is getting third parties (like eg GMail) trusting your setup. It would be important to document a checklist regarding Mail Exchange trust like:

 - [ ] I'm not an open spam relay
 - [ ] MX record registered for my domain
 - [ ] Reverse DNS setted up for MX servers
 - [ ] SPF records setted up
 - [ ] DKIM signature setted up

(which is slightly external to James as DNS setup is required)

**Comment by dleangen** [comment]
That would actually be a very useful thing to "support" for users. If somebody wants to set up their own server, do you think it would be possible for the James community to somehow provide a list like this, and show people what they need to do? Maybe a series of articles or something if these are external to James?

**Comment by chibenwa** [comment]
A "how to" regarding this is a MUST have in my opinion http://james.apache.org/howTo/index.html

**Comment by dleangen** [comment]
Just a thought based on the ideas you wrote here...

But what if the mission of James were to "help people self-host their email" as an alternative to providers like gmail etc.

Right now James is very obscure and is only for total tekkie geeks. If we modify the target, perhaps this could be the mission.

The way of accomplishing this is:
 * Provide in-depth "concept" articles
 * Provide more "how tos" for important things
 * Make James easier to install and operate

wdyt?

**Comment by dleangen** [comment]
So to extend this idea...

I guess instead of James being this:

> James stands for Java Apache Mail Enterprise Server!
> It has a modular architecture based on a rich set of modern and efficient components which provides at the end complete, stable, secure and extendable Mail Servers running on the JVM.
> 
> Create your own personal solution of emails treatment by assembling the components you need thanks to the Inversion of Control mail platform offered and go further customizing filtering and routing rules using James Mailet Container.

It would be more like:

Apache James give you the ability to "self-host" email. Many companies and individuals are unable to develop their own mail infrastructure, but often feel trapped into using services like gmail, yahoo, etc. James provides a low-cost alternative for those who desire the freedom to use email the way they want.

Or something like that.

**Comment by chibenwa** [comment]
> Apache James give you the ability to "self-host" email. Many companies and individuals are unable to develop their own mail infrastructure, but often feel trapped into using services like gmail, yahoo, etc. James provides a low-cost alternative for those who desire the freedom to use email the way they want.

This should be the goal of the Basic server.

Regarding "Advanced server":

```
Free email servers are generaly old, written in complex languages (C) and extending their behavior is not one of there main concerns. 

Apache James Advanced server have been designed with extensibility in mind. It provides several extension mechanisms allowing you to easily configure and extend the behavior of your email server in order to make it fits your needs. Java and other JVM languages can be used to write your own extensions.
```

And for the Apache James Distributed server:

```
Scaling out IMAP mail server is notoriously difficult, as Mail server generally relies on technologies that don't scale well. Apache James server had been designed on top of modern distributed middlewares that allow you to scale it out just like any other modern web applications, reducing the management overhead of large scale deployments.
```

We could be thinking of, regarding the testing server:

```
Embed a tiny, zero external dependency, easy to configure, feature complete, testing mail server to test the email logics for your code. Could be run directly in your JVM tests or spawn via docker.
```

Would that go in your direction?

**Comment by chibenwa** [comment]
> Right now James is very obscure and is only for total tekkie geeks. If we modify the target, perhaps this could be the mission.

For the Basic server we should manage to be less "teckie oriented". 

However "Advanced servers" branding should be compelling for "teckies" and discourage other operators.

**Comment by dleangen** [comment]
Very nice!

That gives me an idea for the naming, then:

* Basic Server (for self-hosting - should be very simple)
* Extendable Server (for customizing - can be more complex)
* Advanced Server (for just about everything else, including "Distributed" - no holds barred)

wdyt?

**Comment by dleangen** [comment]
Just to get even crazier with this idea... we could say that we want to start an email revolution, whereby people will rebel against the current world order (i.e. gmail etc.). :-)

**Comment by chibenwa** [comment]
In the wording above I really prefer the term `Distributed Server` to `Advanced Server` as (as my little description above in https://github.com/ieugen/james-self-hosting-sandbox/issues/9#issuecomment-645168401 demonstrates it) 'distributed server' addresses a all category of advanced users concerns.

I prefer branding the "distributed" term as this is a selling argument.

**Comment by dleangen** [comment]
For the "Extendible Server", what about the difference between "local" and "redundant"? Or should we just skip redundant and go straight to distributed?

**Comment by chibenwa** [comment]
IMO the Advanced server should be configured as local per default but configurable to redundant if needed.

Technically: let's use a default embedded derby database for it, but if needed the operator can connect it with a PostgresSQL server for instance.

**Comment by ieugen** [comment]
This is a very good discussion.
For me, I would like to host my own emails and perhaps host for some companies. 
I think there is room for improvement in the email space.
It's such a basic tool and and has a broad reach.

I also think there is some opportunity for  many more small email setups than large ones.
From what I read, SPAM is one of the limiting factors in this. 

Email architecture is very flexible and there are a lot of reasons why you would prefer one over the other. 
We will never come up with the perfect one.
For the basic service, we should strive for something that people can use out of the box with ease and it is simple to maintain. 

Other specialized use cases
- run on embedded devices (raspberry PI)
- run inside Kubernetes in a distributed manner (alternative to Cassandra)

And the list can go on.

I'm going to focus on scratching my own itch, share what I learn and fix things as I go. 
This is IMO the heart of free software and open source.

**Comment by dleangen** [comment]
I am going to move this discussion from here since this seems to be turning into a private repository. I misunderstood, thinking it was for the James community.
